# Each PR will build preview site that help to check code is work as expect.

name: Build

on:
  # Ручной запуск через GitHub UI
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Тип сборки'
        required: true
        default: 'both'
        type: choice
        options:
        - both
        - pro
        - debug
      retention_days:
        description: 'Дни хранения артефактов'
        required: false
        default: '7'
        type: string
      
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - '*'

jobs:
  # Prepare node modules. Reuse cache if available
  setup:
    name: prepare build
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        id: yarn-node_modules # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Get Yarn Cache
        if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: yarn --prefer-offline

      - name: Use NPM Token with organization read access
        uses: heisenberg-2077/use-npm-token-action@v1
        with:
          token: '${{ secrets.NPM_AUTH_TOKEN }}'

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  build-pro:
    name: build pro
    runs-on: ubuntu-latest
    needs: setup
    # Условие: запускать если выбран pro или both, или если это не ручной запуск
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build_type == 'pro' || github.event.inputs.build_type == 'both' }}
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        id: yarn-node_modules # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: build
        run: yarn build:pro

      - name: Upload artifact (PR)
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: Rabby_${{github.sha}}
          path: dist
          retention-days: 7

      - name: Upload artifact (Push with tag)
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: Rabby_${{github.ref_name}}
          path: dist
          retention-days: 7

      - name: Upload artifact (Manual dispatch)
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          name: Rabby_manual_${{github.sha}}_pro
          path: dist
          retention-days: ${{ github.event.inputs.retention_days || '7' }}

  build-debug:
    name: build debug
    runs-on: ubuntu-latest
    needs: setup
    # Условие: запускать если выбран debug или both, или если это не ручной запуск
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == 'both' }}
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v3
        id: yarn-node_modules # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: build
        run: yarn build:debug

      - name: Upload artifact (PR)
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: Rabby_${{github.sha}}_debug
          path: dist
          retention-days: 7

      - name: Upload artifact (Push with tag)
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: Rabby_${{github.ref_name}}_debug
          path: dist
          retention-days: 7

      - name: Upload artifact (Manual dispatch)
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          name: Rabby_manual_${{github.sha}}_debug
          path: dist
          retention-days: ${{ github.event.inputs.retention_days || '7' }}